### Login 
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "username": "markJohnson",
  "password": "secretpassword"
}




### get images
GET  http://localhost:3000/default_dp.png

### comment reqs
POST http://localhost:3000/api/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmtKb2huc29uIiwicm9sZSI6InVzZXIiLCJfaWQiOiI2NDhmMzIxNmVjMTZmYzViNTMwNDVjNTYiLCJpYXQiOjE2ODcxNzk4MDAsImV4cCI6MTY4NzI2NjIwMH0.CUIygL4rxbgIsyC6Ep6J_NFZdqP3dZCd22pQvRqLMgc

{
    "postId" : "648f5601b0017e980281ed94",
    "description" : "1st comment"
}

### get by post id 
GET http://localhost:3000/api/comment/648f5601b0017e980281ed94
